### ISSUE TITLE
Issue with resolving this `DidDidDetailsDidCreationDetails`

### ISSUE THREAD

**Issue by alvin-reyes** [KILTprotocol/sdk-js#456]
I keep getting this error when creating a new Did. 

```
(node:22890) UnhandledPromiseRejectionWarning: Error: type DidDidDetailsDidCreationDetails not found
    at assert (/Users/brambear/Projects/proofid/sample/node_modules/@polkadot/util/assert.cjs:37:11)
    at TypeRegistry.getOrThrow (/Users/brambear/Projects/proofid/sample/node_modules/@polkadot/types/create/registry.cjs:504:22)
```

If I change it `DidDidDetailsDidCreationDetails` to `DidCreationDetails` it seems to go thru but I was wondering why this isn't up to date or fixed?

https://github.com/KILTprotocol/sdk-js/blob/e0442f920c5b9218eb9e5a109b5dd2d8a4ea82cd/packages/did/src/Did.utils.ts#L258

**Comment by Diiaablo95** [comment]
Hello @alvin-reyes, what SDK version are you using?

**Comment by alvin-reyes** [comment]
> Hello @alvin-reyes, what SDK version are you using?

0.25.0-2

**Comment by Dudleyneedham** [comment]
@alvin-reyes I checked and wasn't able to reproduce the error, which version of the chain are you using?

**Comment by alvin-reyes** [comment]
I'm using the latest on the master branch. Running it on my local machine.

**Comment by Dudleyneedham** [comment]
At the moment, we didn't find a direct issue after investigating it. we are monitoring this issue and will continue to check the progress. Since we have a PR open that will tackle the typing definitions. Perhaps that will solve your issue, and we will let you know once that PR has been submitted.

**Comment by Diiaablo95** [comment]
Hello @alvin-reyes, we have a new release candidate v0.26.0-rc.2 (https://www.npmjs.com/package/@kiltprotocol/sdk-js/v/0.26.0-rc.2). It is an SDK API breaking change, but it does not break compatibility with neither the current nor the upcoming Spiritnet runtime. Among other things, removes custom type definitions and switches completely to chain-generated runtime definition. It might take some time to convert to the new candidate, but it would be good to know whether you could reproduce the issue with the new version?

**Comment by ntn-x2** [comment]
No activity for this ticket. Closing for now.
